### ISSUE TITLE
assetBundles 打不出lua资源的包

### ISSUE THREAD

**Issue by 164638896** [smilehao/xlua-framework#1]
在编辑器模式可以启动游戏。
但是使用AssetBundles打包的启动不了 找不到 lua.assetbundle. 

1.执行XLua->Copy lua files to AssetBundles
2.执行 AssetBundles->Build AssetBundles->For Android
打不出lua文件AssetBundles包。
貌似Ab打包要设置AssetBundleName？ 有没什么工具设置？

ps：unity3d 使用 的是 2017.2.1和5,6.4 这两个版本

**Comment by smilehao** [comment]
更新项目再试试看有没有问题，现在的AB包名字是自动设置的，规则可视化配置
