### ISSUE TITLE
关于子模块单独热更新的一些问题

### ISSUE THREAD

**Issue by yh1094632455** [smilehao/xlua-framework#11]
我想问下如果子模块单独热更新的ab打包怎么弄才好，现在打包是全部打包，启动检测全部热更新，我想渠道.manifest不包含子模块，子模块生成类似渠道那种的manifest和版本文件，大佬有啥好建议吗？渠道里面的map文件还是按照原来的，包括所有资源路径，大佬有啥好建议吗？

**Comment by smilehao** [comment]
为什么不在启动的时候热更而非要在打开模块的时候才热更呢，这么做的用意是什么

**Comment by yh1094632455** [comment]
因为我们游戏里面可能会有子游戏，需要单独打包然后在游戏里面更新

**Comment by smilehao** [comment]
也可以做，不过整个资源管理模块需要做些改动，支持多个manifest
