### ISSUE TITLE
发布到安卓平台，使用assetbundle加载 、报错，找不到csjon

### ISSUE THREAD

**Issue by CircleGood** [smilehao/xlua-framework#17]
![image](https://user-images.githubusercontent.com/16008903/43315023-4e62a7aa-91c7-11e8-876c-4263e835127b.png)

**Comment by CircleGood** [comment]
07-27 17:57:45.241: E/Unity(2400): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
07-27 17:57:45.301: E/Unity(2400): xLua exception : XLua/Common/util.lua:1: module 'cjson' not found:
07-27 17:57:45.301: E/Unity(2400): 	no field package.preload['cjson']
07-27 17:57:45.301: E/Unity(2400): 	no such builtin lib 'cjson'
07-27 17:57:45.301: E/Unity(2400): 	no such file 'cjson' in CustomLoaders!
07-27 17:57:45.301: E/Unity(2400): 	no such resource 'cjson.lua'
07-27 17:57:45.301: E/Unity(2400): 	no file '/usr/local/share/lua/5.3/cjson.lua'
07-27 17:57:45.301: E/Unity(2400): 	no file '/usr/local/share/lua/5.3/cjson/init.lua'
07-27 17:57:45.301: E/Unity(2400): 	no file '/usr/local/lib/lua/5.3/cjson.lua'
07-27 17:57:45.301: E/Unity(2400): 	no file '/usr/local/lib/lua/5.3/cjson/init.lua'
07-27 17:57:45.301: E/Unity(2400): 	no file './cjson.lua'
07-27 17:57:45.301: E/Unity(2400): 	no file './cjson/init.lua'
07-27 17:57:45.301: E/Unity(2400): 	no file '/usr/local/lib/lua/5.3/cjson.so'
07-27 17:57:45.301: E/Unity(2400): 	no file '/usr/local/lib/lua/5.3/loadall.so'
07-27 17:57:45.301: E/Unity(2400): 	no file './cjson.so'
07-27 17:57:45.301: E/Unity(2400): 	no such file 'cjson.lua' in streamingAssetsPath!
07-27 17:57:45.301: E/Unity(2400): stack traceback:
07-27 17:57:45.301: E/Unity(2400): 	[C]: in function 'require'
07-27 17:57:45.301: E/Unity(2400): 	XLua/Common/util.lua:1: in main chunk
07-27 17:57:45.301: E/Unity(2400): 	[C]: in function 'require'
07-27 17:57:45.301: E/Unity(2400): 	XLua/Hotfix/HotfixTest.lua:8: in main chunk
07-27 17:57:45.301: E/Unity(2400): 	[C]: in function 'require'
07-27 17:57:45.301: E/Unity(2400): 	Common/Tools/import.lua:37: in function 'reimport'
07-27 17:57:45.301: E/Unity(2400): 	XLua/HotfixMain.lua:16: in function 'XLua.HotfixMain.Start'
07-27 17:57:45.301: E/Unity(2400): 	[string "chunk"]:1: in main chunk
07-27 17:57:45.301: E/Unity(2400):    at XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) [0x00000] in <filename unknown>

**Comment by smilehao** [comment]
cjson是tolua那边的一个库吧，我当时没有使用到，所以没有迁移过来，你可以自己去编译一下，这个报错是xlua动态库里面没有集成cjson
