### ISSUE TITLE
math.pow 无法使用

### ISSUE THREAD

**Issue by kstg3124776** [smilehao/xlua-framework#2]
math.pow(q,size)  : attempt to call a nil value (field 'pow')
 Mathf.Pow  : attempt to call a nil value (field 'Pow')
版本是2017.3.1 试了几下就是次方的用不了 很奇怪 ：(

**Comment by smilehao** [comment]
lua的math库没有pow这个函数；Mathf.Pow是代码写的有点问题，你更新下再试试
