### ISSUE TITLE
我在Lua序列化化pb后的是一个字符串。但是如何转成byte[]传到c#端呢，直接传过去回报类型不符合

### ISSUE THREAD

**Issue by sevenLa** [smilehao/xlua-framework#21]
lua 端-------------------------------------------

local msg = (require("Net.Pb.admin_pb")).req_exec_cmd()
msg.cmd = "这是一个测试PB"
local pb_data = msg:SerializeToString()

C#端--------------------------------------------

 public Action<byte[]> ReceivePkgHandle = null;
  public void HjTcpNetwork(byte[] msgObj)
   {
            
             
   }

**Comment by smilehao** [comment]
将typeof(Action<byte[]>)添加到CSharpCallLua
