### ISSUE TITLE
几处有疑问的地方

### ISSUE THREAD

**Issue by zhangximing** [smilehao/xlua-framework#22]
![1](https://user-images.githubusercontent.com/1566910/43999764-7aaeb0f8-9e45-11e8-9770-3f6df29e47cd.png)

如图在LoadAssetBundleAsync中对依赖包添加了引用，我的理解是这里的引用应该是loader来持有，但是loader在OnProsessingAssetBundleAsyncLoader 中只是解除了对当前assetbundle的引用持有，却没有处理依赖的持有

**Comment by zhangximing** [comment]
![1](https://user-images.githubusercontent.com/1566910/43999806-662100d6-9e46-11e8-9851-650515f55ddd.png)
![2](https://user-images.githubusercontent.com/1566910/43999807-67478c78-9e46-11e8-9b46-784989ef2cf6.png)
这里感觉也有点疑问，TryUnloadAssetBundle中只处理引用计数小于或等于0的情况，但是其调用的UnloadAssetBundle对于引用计数小于等于0的情况直接不处理了，自相矛盾

**Comment by smilehao** [comment]
1、如图在LoadAssetBundleAsync中对依赖包添加了引用，我的理解是这里的引用应该是loader来持有，但是loader在OnProsessingAssetBundleAsyncLoader 中只是解除了对当前assetbundle的引用持有，却没有处理依赖的持有
    for循环内部的引用计数，记的是被依赖的AB被依赖者持有的引用，具体来说，如果A依赖于B，则加载A时B必须也被加载，所以A对B持有引用---这么设计的目的是，如果A没卸载，但是B却被卸载了，那么从A中加载的资源就会出错，所以这个引用关系可以保证A没被卸载时，它里面的资源都是安全可靠的；函数尾部的引用计数才和你理解的一致，被loader持有，还是假设A依赖B，loader的目标是A，那么loader过程中A的引用计数不为0，可以保证loader过程中不出现卸载的情形，当loader结束以后，A使用完毕，A的引用技术变成0，A就可以被卸载，说明需要从A中加载的资源已经成功被加载。这里要注意，loader过程中loader对A持有引用，A对B持有引用，loader结束后A计数为0被卸载，A被卸载的过程中会对所有依赖项减掉引用计数，此时B的引用计数也会恢复到0而被自动卸载。

2、这里感觉也有点疑问，TryUnloadAssetBundle中只处理引用计数小于或等于0的情况，但是其调用的UnloadAssetBundle对于引用计数小于等于0的情况直接不处理了，自相矛盾
    TryUnloadAssetBundle这个接口实际上没有调用它的地方，C#这本只被xlua导出代码引用到，而xlua侧也没用到，这个接口设定是有问题的，非常驻AB会在引用计数为0的时候自动被卸载掉，而提供手动卸载的接口，是为了主动去卸载常驻AB包，因为它们引用计数为0也不会被自动卸载，相反，必须引用计数为0，尝试卸载才应该成功，因为不为0肯定是有被其它AB包需要的。这个接口我删掉它吧，用UnloadUnusedAssetBundles去取代。

引用计数这边的代码有点乱，我正在重构，争取今天搞定。。。

**Comment by smilehao** [comment]
已经调整好了
