### ISSUE TITLE
项目大概流程

### ISSUE THREAD

**Issue by mahuibao01** [smilehao/xlua-framework#31]
非常感谢楼主的这个项目，让我学习了很多。
然后我作为一个入行半年的新人，依旧有些东西无法理解太多。
往楼主能给个编写这个框架的大体流程。
一边参考楼主的，一边我也在想着自己慢慢写一个自己完全掌握的框架。
因为我接触的知识点太少了，甚至有些都不知道是啥。
我的想法是例如：1.xlua的引入。2.xlua的第三方库引入。3.xlua在c#侧的扩展与功能完善修改。4.protobuf的引入等等。。
我是个小白，也许我的问题很幼稚，但是还是忍不住想问。

**Comment by smilehao** [comment]
这些问题可以去网上找相关信息，我也不是几句话就能够说清楚。我简单描述下吧。

1、Unity使用C#脚本语言，导致代码没法在iOS上热更新（Andorid可以通过更新DLL文件来更新代码），所以开发者引入了Lua脚本语言来做这个事情，Lua热更新方案市面上使用较多的是cstolua和xlua

2、所有lua热更方案都少不了几个基础的东西，包括Lua解释器，Lua和CS通讯的封装，来方便开发者使用。xlua是作为“使用CS语言开发，Lua语言来修复Bug”的初衷设计出来的，它只提供基础的一些功能，为了保证核心功能简洁，比如像pb库、json解析库等第三方库就没有集成进来，而且这些第三方库的选择很大程度上由开发者项目本身来决定，所以第三方库引入的概念就是你需要什么额外的lua功能，你自己再去集成第三方库进来。

3、lua和CS交互存在性能问题，而优化的途径之一就是尽量降低Lua和CS的相互调用，而xlua在c#侧的扩展与功能完善修改怎么说，比如你需要一个Vector3.Lerp功能，你可以在Lua侧调用CS的Vector3接口来实现，但是这里就必须牵涉到Lua到CS的调用，所以，为了避免这些调用开销，可以在Lua侧写一样的逻辑来做这个Lerp的功能，减少与CS的交互，来打到提高性能的目的。

4、protobuff直接谷歌吧。。。这是一个太大众的话题，一句话说就是一种网络数据交换协议，通俗点说就是客户端与服务端通讯时使用的一种协议。
