### ISSUE TITLE
UIImage的封装只支持散图，打成一个png，multisprite没支持？

### ISSUE THREAD

**Issue by wanwanyahoo** [smilehao/xlua-framework#32]
没看到图集一个png，多个sprite的读取支持，工程里示例也是散图，求改动

**Comment by smilehao** [comment]
没听懂，你是要求改动啥。。。看起来像是你误会了，UGUI图集不是NGUI图集，它本来就是一个个散图，打包以后会合并drawcall的，不需要担心，Unity这样设计本来就是为了弱化图集的概念，不需要像NGUI那样总是要在开发过程中去维护图集。
打开菜单window->Sprite Packer窗口，左上角有个“Repack”按钮，点击一下，等它打完你就可以在这里预览所有的图集了。
