### ISSUE TITLE
BUG: package_name.bytes内容错误

### ISSUE THREAD

**Issue by magianliu** [smilehao/xlua-framework#4]
错误
ArgumentException: The requested value 'E:\DevelProject\xLua\xlua-framework-master\AssetBundles\Android\Test' was not found.
System.Enum.Parse (System.Type enumType, System.String value, Boolean ignoreCase) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Enum.cs:692)
System.Enum.Parse (System.Type enumType, System.String value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Enum.cs:547)
GameChannel.ChannelManager.CreateChannel (System.String packageName) (at Assets/Scripts/Channel/ChannelManager.cs:55)
GameChannel.ChannelManager.Init (System.String packageName) (at Assets/Scripts/Channel/ChannelManager.cs:50)
GameLaunch+<InitPackageName>c__Iterator2.MoveNext () (at Assets/Scripts/GameLaunch/GameLaunch.cs:107)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

查看源码是 ChannelManager.instance.Init(packageName);出错
加日志发现 packageName 为 E:\DevelProject\xLua\xlua-framework-master\AssetBundles\Android\Test，渠道应该是 Test
这个是从 package_name.bytes中读出来的，应该是产生这个文件时就出错了。

修改BuildPlayer.cs的BuildAssetBundlesForCurSetting方法：
var outputPath = PackageUtils.GetCurBuildSettingOutputPath();
       BuildAssetBundles(buildTarget, outputPath);
改为
        string channelName = PackageUtils.GetCurSelectedChannel().ToString();
        BuildAssetBundles(buildTarget, channelName);
这是因为BuildAssetBundles的第2个参数需要的是渠道名

**Comment by smilehao** [comment]
嗯嗯，已修改
