### ISSUE TITLE
coroutine.waitforasyncop 在IL2CPP下无法正常执行完毕

### ISSUE THREAD

**Issue by insama** [smilehao/xlua-framework#46]
coroutine.waitforasyncop 在IL2CPP下无法正常执行完毕，2018和2019都出现了这个问题。启动切换场景的时候必出。

**Comment by passiony** [comment]
相同的问题，请问楼主怎么解决的？

**Comment by insama** [comment]
> 相同的问题，请问楼主怎么解决的？

#48 看这里

**Comment by passiony** [comment]
因为AsyncOperation没有生成Wrap文件，所以lua找不到它的progress属性。
已解决：给AsyncOperation类添加LuaCallCSharp标签
