### ISSUE TITLE
工程直接导出到xcode 打包真机报错 

### ISSUE THREAD

**Issue by a463672729** [smilehao/xlua-framework#50]
![图片](https://user-images.githubusercontent.com/9668698/67449684-8a04dd00-f64d-11e9-9cc7-02cd701b171c.png)
已经设置了ip为本机ip  并且也切换到了simulate了  

查看代码发现这里的url是空的  请问这个是干嘛用的  可以注掉不
![图片](https://user-images.githubusercontent.com/9668698/67450744-f9300080-f650-11e9-951d-85b27d3001e1.png)
![图片](https://user-images.githubusercontent.com/9668698/67450756-051bc280-f651-11e9-80e9-a9eaa99e4e7a.png)

**Comment by passiony** [comment]
这是上报日志的，如果不需要往服务器端上报日志，可以注释掉
