### ISSUE TITLE
mac电脑运行报错404

### ISSUE THREAD

**Issue by passiony** [smilehao/xlua-framework#51]
使用mac电脑运行项目，editor模式下没有问题，但是simulator下就会报404错。错误发生在：启动资源管理模块时->1.加载Assetbundle文件。实际是webRequesting的url出了问题。

**Comment by passiony** [comment]
解决方案：
var url = AssetBundleUtility.GetAssetBundleFileUrl(assetbundleName);
这个方法是获取本地的Assetbundle文件，如果PersistentAsset目录有就直接读取，否则从StreamingAsset目录读取，但是GetPersistentDataPath这个方法中对路径做了一个/转\\的处理，见此方法GameUtility.FormatToSysFilePath(outputPath)，这个转换只需要在pc执行就可以了，所以把#if UNITY_EDITOR替换成#if UNITY_STANDALONE_WIN，这样mac下就不会再去替换/了。

**Comment by smilehao** [comment]
改UNITY_EDITOR_WIN
