### ISSUE TITLE
关于BaseClass 析构函数的问题

### ISSUE THREAD

**Issue by MagicLizi** [smilehao/xlua-framework#52]
从BaseClass 的代码上看 是通过 obj.Delete 来触发析构函数的

但是并没有 obj.Delete 在被gc 之后的调用..所以不知道这边是怎么处理的

自己尝试了一下，强制gc 后并不触发对象的__delete

**Comment by passiony** [comment]
lua的对象，你给他赋值为nil，会自动gc的
__delete在本框架中指的的析构函数，如非必要，尽量别重写。如果重写了，需要你手动调用Delete方法才会调用析构__delete。

**Comment by MagicLizi** [comment]
但是框架中很多 继承自 BaseClass 类都 重写了 __delete,但貌似并没有找到有地方手动调用Delete- -不知道这边的__delete 是如何触发的

**Comment by MagicLizi** [comment]
好的感谢，我找到了！

**Comment by smilehao** [comment]
lua并没与真正的面向对象设计，lua里的表实际上也不是对象，这里的面向对象设计只是模拟了c++虚表的设计来实现的，所以表格在gc时没有lua系统层面的“回调”
