### ISSUE TITLE
Unity 2018.4.15无法运行，一堆报错，切换成安卓平台还是报错

### ISSUE THREAD

**Issue by icecoldless** [smilehao/xlua-framework#54]
![QQ图片20200318141027](https://user-images.githubusercontent.com/32491042/76930805-4d01f580-6922-11ea-8beb-485b2a58e6bd.png)
![QQ图片20200318141039](https://user-images.githubusercontent.com/32491042/76930811-50957c80-6922-11ea-9550-2a75747a84a1.png)

**Comment by Cabriter** [comment]
我也遇到了这个问题，是怎么解决的？

**Comment by passiony** [comment]
解决：https://github.com/passiony/xlua-framework-unity2018
