### ISSUE TITLE
错误修改

### ISSUE THREAD

**Issue by magianliu** [smilehao/xlua-framework#6]
在PackageTool里生成AssetBundles后出现错误，PackageTool的UI就不能显示了。AssetBundles已经生成完成。

get_activeBuildTarget is not allowed to be called from a ScriptableObject constructor (or instance field initializer), call it in OnEnable instead. Called from ScriptableObject 'PackageTool'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEditor.EditorUserBuildSettings:get_activeBuildTarget()
PackageTool:.cctor() (at Assets/Editor/PackageBuild/PackageTool.cs:19)

我的修改

public class PackageTool : EditorWindow
{
    static private BuildTarget buildTarget = BuildTarget.Android;
    static private ChannelType channelType = ChannelType.Test;
    static private string resVersion = "1.0.0";
    static private LocalServerType localServerType = LocalServerType.CurrentMachine;
    static private string localServerIP = "127.0.0.1";

    static PackageTool()
    {
        //buildTarget = EditorUserBuildSettings.activeBuildTarget;
        //channelType = PackageUtils.GetCurSelectedChannel();

        //localServerType = PackageUtils.GetLocalServerType();
        //localServerIP = PackageUtils.GetLocalServerIP();
    }

    void OnEnable()
    {
        buildTarget = EditorUserBuildSettings.activeBuildTarget;
        channelType = PackageUtils.GetCurSelectedChannel();

        localServerType = PackageUtils.GetLocalServerType();
        localServerIP = PackageUtils.GetLocalServerIP();
    }

**Comment by smilehao** [comment]
已采用，谢谢

**Comment by SPingels** [comment]
ConfigTools.cs存在相同的问题~

**Comment by smilehao** [comment]
已采用
